title: Archish Srinivasan
description: Just another tech enthusiast, jotting down my thoughts here
remote_theme: mmistakes/minimal-mistakes@4.27.1

# Base URL if hosted in /blog subdir
baseurl: /blog
url: https://archish85.github.io  # Replace this

author:
  name: Archish Srinivasan
  avatar: https://i.postimg.cc/MZ74zVdg/A-digital-illustration-compressed.png
  bio: Just another tech enthusiast, jotting down my thoughts here

# Social Links
social:
  twitter: archish85
  github: https://github.com/archish85/
  linkedin: https://www.linkedin.com/in/archish85/
  rss: true

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-include-cache

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: /:title/
