title:              Archish Srinivasan
email:              archish85@gmail.com
description:        Just jotting down my thoughts and ideas v2
author:             Archish Srinivasan
baseurl:            "/blog"
url:                ""

# Social Profiles
twitter_username:   archish85
github_username:    archish85
facebook_username:  archish85
instagram_username:  
linkedin_username: archish85

# Add your google-analytics ID here to activate google analytics
#google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
